urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
#from dashboards.urls import register
from dashboards import get_urlpatterns
from dashboards.views import login,logout,get_user_home


urlpatterns = [
    url(r'^$', get_user_home, name='home'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'', include(get_urlpatterns() ) ),
]

urlpatterns += [
    url(r'^admin/login/$', RedirectView.as_view(url='/login/', permanent=True), name='go-to-login'),
    url(r'^admin/logout/$', RedirectView.as_view(url='/logout/', permanent=True),name='go-to-logout' ),
    url(r'^admin/', include(admin.site.urls)),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboards/project/brm/models.py
#coding:utf-8
import os
import yaml
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from ansible.module_utils._text import to_text
from dashboards.project.general.models import Machine
from utils.ansibclient import AnsibleAPI

    
class CommonModel(models.Model):

    created_by = models.CharField(max_length=30)
    created_time = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Template(CommonModel):
    """
    A publish template is a reusable job definition for applying a project (with
    playbook).
    """
    name = models.CharField(unique=True, max_length=30)
    profile = models.CharField(max_length=100)
    handlers = models.TextField(null=True, blank=True)
    playbook = models.TextField()
    
    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name = 'Template'
        verbose_name_plural = verbose_name
      
    @classmethod
    def get_template(cls, name=None):
        return cls.objects.all() if not name else cls.objects.filter(name=name).all()
        
    def get_profiles(self, host, user):
        machine = Machine.objects.get(ssh_ip=host)
        ansib = AnsibleAPI([{
            'host': machine.ssh_ip, 
            'port': machine.ssh_port, 
            'user': user,
        }])
        result = ansib.exec_shell( "ls -l %s | grep ^-" % self.profile )
        if result[host]['status'] != 'ok':
            out = result[host]['result']['stderr']
        else:
            stdout_lines = result[host]['result']['stdout_lines']
            out = [ os.path.join(self.profile,line.split(' ')[-1]) for line in stdout_lines ]
        return {'status': result[host]['status'], 'out': out }
        
    def get_profile_content(self, app_name, **kwargs):
        machine = Machine.objects.get(ssh_ip=kwargs['host'])
        ansib = AnsibleAPI([{
            'host': machine.ssh_ip, 
            'port': machine.ssh_port, 
            'user': kwargs['user'],
        }])
        local_path = os.path.join(
            settings.CONFIGURE_BACKUP, 
            app_name,
            #'{{ inventory_hostname }}',
            os.path.basename(kwargs['filepath']) )
        return ansib.get_file(kwargs['filepath'],  local_path)
        
    def save_profile_content(self, region, **kwargs):
        resource = []
        if 0 == int(region):
            host = kwargs.get('host')
            machine = Machine.objects.get(ssh_ip=host)
            resource.append({
                'host': machine.ssh_ip, 
                'port': machine.ssh_port, 
                'user': kwargs.get('user'),
            })
        else:
            nodes = kwargs.get('nodes')
            for node in nodes:
                resource.append({
                    'host': node.machine.ssh_ip, 
                    'port': node.machine.ssh_port, 
                    'user': kwargs.get('user'),
                })
        ansib = AnsibleAPI(resource)
        remote_path = os.path.join(self.profile, kwargs['configure_file_name'] )
        return ansib.put_file(kwargs['filepath'], remote_path )
        
    def get_handlers(self, optype=None):
        handlers_dict = {}
        handlers = yaml.load(self.handlers) if self.handlers else []
        map(lambda handler: handlers_dict.update(handler), handlers )
        if optype:
            return handlers_dict.get(optype)
        return handlers_dict
        
    def do_handle(self, name, resource, optype, uid, url ):
        handlers_dict = {}
        handlers = yaml.load(self.handlers) if self.handlers else []
        map(lambda handler: handlers_dict.update(handler), handlers )
        info = handlers_dict.get(optype)
        ansib = AnsibleAPI(resource)
        return ansib.exec_timely_command( info[0]['cmd'], url, name, uid )
        
        
class AppNode(models.Model):
    """
    Application publishing node.
    """
    app = models.ForeignKey("App", on_delete=models.CASCADE)
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'AppNode'
        verbose_name_plural = verbose_name
        
   
@python_2_unicode_compatible        
class Plugin(CommonModel):
    """
    Plug-ins that may be required during the distribution process.
    """
    app = models.ForeignKey("App", null=True, blank=True, on_delete=models.SET_NULL)
    pre_release = models.TextField()
    post_release = models.TextField()
    
    def __str__(self):
        return self.app.publish_name
        
    class Meta:
        verbose_name = 'Plugin'
        verbose_name_plural = verbose_name

        
@python_2_unicode_compatible
class App(CommonModel):
    """
    Application information
    """
    status = (
        (1, 'offline'),
        (2, 'online'),
        (3, 'unknown'),
    )
    
    publish_name = models.CharField(unique=True, max_length=30)
    publish_alias = models.CharField(unique=True, max_length=30)
    publish_type = models.ForeignKey("Template", null=True, blank=True, on_delete=models.SET_NULL)
    publish_user = models.CharField(max_length=30)
    publish_path = models.CharField(max_length=1024,default='',)
    publish_scmurl = models.URLField(blank=False)
    publish_num = models.IntegerField( null=True, blank=True )
    publish_status = models.IntegerField( choices=status, default=1)
    publish_time = models.DateTimeField(default=timezone.now)
    publish_runstat = models.IntegerField( choices=status, default=1)
    current_version = models.CharField(null=True, blank=True, max_length=30)
    
    def __str__(self):
        return "%s(%s)" % (self.publish_alias, self.publish_name)
        
    class Meta:
        verbose_name = 'App'
        verbose_name_plural = verbose_name
        
    def run_playbook(self, extra_vars={} ):
        resource = []
        nodes = AppNode.objects.filter(app_id = self.id).all()
        for node in nodes:
            resource.append({
                'host': node.machine.ssh_ip, 
                'port': node.machine.ssh_port, 
                'user': self.publish_user,
                'pass': 'service!@#'
            })   
        ansib = AnsibleAPI(resource)
        cache_key = os.path.join(os.getcwd(), self.publish_type.name)
        file_data = to_text(self.publish_type.playbook, errors='surrogate_or_strict')
        parsed_data = ansib.loader.load(data=file_data, file_name=self.publish_type.name, show_content=True)
        ansib.loader._FILE_CACHE[cache_key] = parsed_data
        return ansib.run_playbook([self.publish_type.name, ], extra_vars )
        
 
@python_2_unicode_compatible 
class Record(CommonModel):
    """
    Application operation record.
    """
    status = (
        (1, 'SUCCESS'),
        (2, 'FAILED'),
    )
    app = models.ForeignKey("App", null=True, blank=True, on_delete=models.SET_NULL)
    action = models.CharField(null=True, blank=True, max_length=30)
    status = models.IntegerField( choices=status, default=1)
    details = models.TextField()
    
    def __str__(self):
        return self.app.publish_name
        
    class Meta:
        verbose_name = 'Record'
        verbose_name_plural = verbose_name
    
    
    
    

templates/brm/brm_add.html
{% extends 'base.html'%}

{% block head %}
<link href="/static/plugins/wizard/bwizard.css" rel="stylesheet" />
{% endblock %}

{% block content %}

<section class="content">

	<div class="box box-default">
      <form id="commentForm" method="post" class="form-horizontal">
        <div id="wizard">
            <ul>
                <li><a href="#tab1" data-toggle="tab"><span class="label">1</span>基础属性</a></li>
                <li><a href="#tab2" data-toggle="tab"><span class="label">2</span>目标机器</a></li>
                <li><a href="#tab3" data-toggle="tab"><span class="label">3</span>高级设置</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <div class="form-horizontal" style="padding: 20px;" >
                        <div class="form-group">
                            <span class="col-sm-2 control-label" >应用名称</span>
                            <div class="col-sm-4" >
                                <input type="text" name="publish_name" class="form-control" placeholder="英文名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-sm-2 control-label">中文名称</span>
                            <div class="col-sm-4">
                                <input type="text" name="publish_alias" class="form-control" >
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-sm-2 control-label" for="ttype" >应用类型</span>
                            <div class="col-sm-4">
                                <select class="form-control" name="publish_type" >
                                    <option value="">请选择应用类型</option>
                                    {% for publish_type in publish_types %}
                                    <option value="{{publish_type.id}}">{{publish_type.name}}</option>
                                    {% endfor %}
                                </select>
                                <!--<input type="text" name="ptype" class="form-control" > -->
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-sm-2 control-label">Git/Svn地址</span>
                            <div class="col-sm-4">
                                <input type="text" name="publish_scmurl" class="form-control" >
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-sm-2 control-label">发布路径</span>
                            <div class="col-sm-4">
                                <input type="text" name='publish_path' class="form-control" >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab2">
                    <div class="form-horizontal" style="padding: 20px;">
                        <div class="form-group">
                            <span class="col-sm-2 control-label">用户</span>
                            <div class="col-sm-6" >
                                <select id="publish_user" name="publish_user" class="form-control">
                                    <option value="">请选择用户</option>
                                    {% for publish_user in publish_users %}
                                    <option value="{{publish_user.user_id}}">{{publish_user.user_id}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-sm-2 control-label">机器列表</span>
                            <div class="col-sm-3" style="width: 24%">
                                <select id="source" multiple class="form-control" size=12>
                                </select>
                            </div>
                            <div class="col-sm-1" style="margin: 0 -1.8% 0 -1.2%">
                                <div style="padding: 66px 0 10px 0;">
                                    <input type="button" id="btn_add" value="&gt;&gt;" />
                                </div>
                                <input type="button" id="btn_remove" value="&lt;&lt;"/>
                            </div>
                            <div class="col-sm-3" style="margin-left: -3%;width: 24%">
                                <select id="target" multiple class="form-control" size=12 >
                                    
                                </select>
                            </div>
                            <input type="hidden" id="publish_machine" name="publish_machine" />
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab3">
                    <div class="form-horizontal" style="padding: 20px;">
                        <div class="form-group">
                            <span class="col-sm-2 control-label">pre_deploy</span>
                            <div class="col-sm-6" >
                                <textarea class="form-control" rows="8" placeholder="Enter ..."></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-sm-2 control-label">post_deploy</span>
                            <div class="col-sm-6" >
                                <textarea class="form-control" rows="8" placeholder="Enter ..."></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="pager wizard">
                    <li class="previous first" style="display:none;"><a href="#">First</a></li>
                    <li class="previous"><a href="#">Previous</a></li>
                    <li class="next last" style="display:none;"><a href="#">Last</a></li>
                    <li class="next"><a href="#">Next</a></li>
                    <li class="finish" style="float: right;"><a href="javascript:;">Finish</a></li>
                </ul>
            </div>
        </div> <!--<wizard-->
      </form>
	</div>
</section>

{% endblock %}

{% block script %}
<script src="/static/js/jquery.validate.min.js"></script>
<script src="/static/plugins/wizard/jquery.bootstrap.wizard.min.js" type="text/javascript"></script>
<script type="text/javascript">
    var $validator = $("#commentForm").validate({
		  rules: {
		    publish_name: { required: true },
            publish_alias: { required: true },
		    publish_type: { required: true },
		    //repos: { required: true },
            publish_path: { required: true,},
            target: { required: true, }
		  }
	});
    $('#wizard').bootstrapWizard({
        'tabClass': 'bwizard-steps', 
        onTabClick: function(tab, navigation, index) {
            return false;
        },
        'onNext': function(tab, navigation, index) {
            var $valid = $("#commentForm").valid();
            if(!$valid) {
                $validator.focusInvalid();
                return false;
            }
        }
    });
    $("#btn_add").click(function(){
        $("#source").find("option:selected").each(function(){
            $(this).appendTo("#target");
        });
    });    
    $("#btn_remove").click(function(){
        $("#target").find("option:selected").each(function(){    
            $(this).appendTo("#source");
        });
    });
    $("#publish_user").change(function(){ 
        console.log(this.value);
        $.get("/brm/machine/", {"ssh_username": this.value }, function(data) {
            for ( var i=0; i<data.length; i++ ) {
                $("#source").append('<option value="' + data[i][0] + '">'+ data[i][1] + '</option>')
            }
        }, "json")
        .error(function() { alert("网络异常，请稍后再试！"); })
    })
    $('#wizard .finish').click(function() {
        var publish_machine = "";
        $("#target option").each(function(){
            publish_machine += $(this).val() + ",";
        })
        $("#publish_machine").val(publish_machine) ;
        $("#commentForm").submit()
	});
</script>
{% endblock %}

templates/brm/brm_list.html
{% extends 'base.html'%}

{% block head %}
<link rel="stylesheet" href="/static/plugins/timepicker/bootstrap-timepicker.min.css">
{% endblock %}


{% block content %}

<section class="content">
    

        <div class="box">
            <div class="box-header">
              <h3 class="box-title"></h3>
                
              <div class="box-tools">
                <div class="input-group input-group-sm pull-left" style="margin-right:5px;" >
                    <button type="button" class="btn btn-default btn-sm" onclick="location.href='/brm/add/'" >
                        <i class="fa fa-fw fa-plus"></i>添加应用</button>
                    </button>
                </div>
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <table class="table table-bordered">
                <tr>
                  <th style="width: 10px">#</th>
                  <th>应用名称</th>
                  <th>中文名称</th>
                  <th>节点数量</th>
                  <th>代码版本</th>
                  <th>应用状态</th>
                  <th>创建者</th>
                  <th>创建时间</th>
                  <th>操作</th>
                </tr>
                {% for app in apps %}
                <tr>
                    <td>{{app.id}}</td>
                    <td>{{app.publish_name}}</td>
                    <td>{{app.publish_alias}}</td>
                    <td>{{app.publish_num}}</td>
                    <td>{{app.current_version}}</td>
                    <!--<td>{{app.get_publish_runstat_display}}</td> -->
                    <td id="app_{{app.id}}_status">
                        <span class="badge bg-light-blue">{{app.get_publish_status_display}}</span>
                        <div class="progress progress-xs" style="display:none;">
                            <div class="progress-bar progress-bar-danger" id="progress-bar-{{app.id}}" style="width: 0%"></div>
                        </div>
                    </td>
                    <td>{{app.created_by}}</td>
                    <td>{{app.created_time}}</td>
                    <td>
                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/brm/update/?id={{app.id}}'">编辑</button>
                        <button type="button" class="btn btn-danger  btn-xs" onclick="location.href='/brm/delete/?id={{app.id}}'">删除</button>
                        <button type="button" class="btn btn-success  btn-xs" id="open_release_modal" >发布</button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
                                更多
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/brm/configure/?id={{app.id}}">服务配置</a></li>
                                <li><a href="/brm/servercontrol/?id={{app.id}}">启停服务</a></li>
                                <li><a href="#">启停监控</a></li>
                                <li><a href="/brm/record/?id={{app.id}}">发布记录</a></li>
                            </ul>
                        </div>
                  </td>
                </tr>
                {% endfor %}
              </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">&laquo;</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">&raquo;</a></li>
              </ul>
            </div>
        </div>
        <!-- /.box -->
        

        <div id="release-modal" class="modal">
          <div class="modal-dialog">
            <div class="modal-content">
             
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">版本发布</h4>
              </div>
              <div class="modal-body">
                <form id="ReleaseForm" class="form-horizontal" method="post" >
                  <div class="form-group">
                    <div class="col-sm-2" style="border-right: 2px solid #ddd;">
                        <label class="control-label">定时发布</label>
                    </div>
                    <div class="col-sm-10">
                         <label class="radio-inline">
                             <input type="radio" name="time" value="1"> 是
                         </label>
                         <label class="radio-inline">
                             <input type="radio" name="time" value="0"> 否
                         </label>
                    </div>
                  </div>
                  <div class="bootstrap-timepicker">
                    <div id="settime" class="form-group" style="display: none;" >
                        <div class="col-sm-2" style="border-right: 2px solid #ddd;">
                            <label class="control-label">设置时间</label>
                        </div>
                        <div class="col-sm-10" >
                            <div class="input-group" style="width: 50%;" >
                                <input type="text" class="form-control timepicker" >
                                <div class="input-group-addon">
                                <i class="fa fa-clock-o"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-2" style="border-right: 2px solid #ddd;">
                        <label class="control-label">消息通知</label>
                    </div>
                    <div class="col-sm-10">
                        <div class="checkbox">
                            <label><input type="checkbox" name="notice" value="1">短信</label>
                            <label><input type="checkbox" name="notice" value="2">邮件</label>
                        </div>
                    </div>
                  </div>
                </form>
           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
             <button type="button" id="brm_release" class="btn btn-primary">确认发布</button>
           </div>
         </div>
         <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

</section>

{% endblock %}

{% block script %}
<script src="/static/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script>

    $(document).ready( function() {
    
        var socket;
        var value=0;
        var uuid = getGuid( (new Date()).valueOf() );
        connect( uuid );
        
         //Timepicker
        $(".timepicker").timepicker({
            showInputs: false
        });
        
        $(":radio[name='time']").click(function(){
            if ( 1 == parseInt( $(this).val() ) ) {
                $("#settime").show();
            } else {
                $("#settime").hide();
            }
        });
        
        $("#open_release_modal").click(function(){
            var appid = $(this).parents('tr').children().eq(0).text();
            var appname = $(this).parents('tr').children().eq(1).text();
            $(".modal-title").text(appname + "版本发布");
            var form = $("#ReleaseForm");
            var input = $("<input type='hidden'>");
            input.attr({"name":"appid"});
            input.val(appid);
            form.append(input);
            var input = $("<input type='hidden'>");
            input.attr({"name":"uuid"});
            input.val(uuid);
            form.append(input);
            $("#release-modal").modal('show');
        });
        
        $("#brm_release").click(function(){
            var appid = $("#ReleaseForm input[name='appid']").val();
            $.ajax({    
                type: 'post',
                dataType:'json',
                url: '/brm/release/',
                data: $('#ReleaseForm').serialize(),
                success:function(data){   
                    if (data.code == 1) {
                        $("#release-modal").modal("hide");
                        $("#app_" + appid + "_status span").hide();
                        $("#app_" + appid + "_status .progress").show();
                    } else {
                        alert(data.msg);
                    }
                }    
            });    
        });
        
        function getGuid(digit) {
            var s = [];
            var hexDigits = "0123456789abcdef";
        
            var len = digit.length;
            if ( len > 16 ) {
                hexDigits = digit.substring(0,15)
            } else if ( len < 16 ) {
                hexDigits = digit
                for(var i=0;i<(16-len);i++){
                    hexDigits += "0"
                }
            }
            for (var i = 0; i < 36; i++) {
                s[i] = hexDigits.substr(Math.floor(Math.random() * 0x10), 1);
            }
            s[14] = "4";  // bits 12-15 of the time_hi_and_version field to 0010
            s[19] = hexDigits.substr((s[19] & 0x3) | 0x8, 1);  // bits 6-7 of the clock_seq_hi_and_reserved to 01
            s[8] = s[13] = s[18] = s[23] = "-";
                
            return s.join("");
        }
        
        function connect(uuid) {
            var host = "ws://192.168.75.131:9000/channel?udid=" + uuid;
            console.log(host)
            socket = new WebSocket(host);
                
            try {
        
                socket.onopen = function (msg) {
                    console.log("connected！");
                };
        
                socket.onmessage = function (msg) {
                    if (typeof msg.data == "string") {
                        //console.log(  msg.data );
                        var current_value;
                        d = JSON.parse(msg.data);
                        console.log(d)
                        if (d.plus == 1) {
                            value += d.value
                            current_value = value
                        } else {
                            current_value = d.value + value;
                        }
                        var rate = ( parseFloat(current_value)/parseFloat(d.allsize) ) * 100
                        if( parseInt(rate) == 100 ) {
                            window.location.reload();
                        }
                        $("#progress-bar-" + d.appid ).css("width", rate.toFixed(2)+'%' );
                        console.log(  rate.toFixed(2) );
                    }
                    else {
                        alert("non-text message.");
                    }
                };
        
                socket.onclose = function (msg) { console.log( msg) };
            }
            catch (ex) {
                log(ex);
            }
        }
    
        window.onbeforeunload = function () {
            try {
                socket.close();
                socket = null;
            }
            catch (ex) {
            }
        };
    
    })
        
</script>
{% endblock %}

templates/brm/brm_record.html
{% extends 'base.html'%}


{% block content %}

   <!-- Main content -->
    <section class="content">

      <!-- row -->
      <div class="row">
        <div class="col-md-12">
          <!-- The time line -->
          <ul class="timeline">
            <!-- timeline time label -->
            <!--<li class="time-label">
                  <span class="bg-green">
                    01 Feb. 2019
                  </span>
            </li> -->
            {% for record in records %}
            <!-- /.timeline-label -->
            <!-- timeline item -->
            <li>
              <i class="fa fa-user bg-aqua"></i>

              <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> {{record.created_time}}</span>

                <h3 class="timeline-header"><a href="#">{{record.get_status_display}}</a> deploy by {{record.created_by}}</h3>

                <div class="timeline-body">
                  {{record.details}}
                </div>
              </div>
            </li>
            {% endfor%}
            <!-- END timeline item -->
            <li>
              <i class="fa fa-clock-o bg-gray"></i>
            </li>
          </ul>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      
    </section>
    <!-- /.content -->

{% endblock %}

{% block script %}
<script>
    
</script>
{% endblock %}