urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
#from dashboards.urls import register
from dashboards import get_urlpatterns
from dashboards.views import login,logout,get_user_home


urlpatterns = [
    url(r'^$', get_user_home, name='home'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'', include(get_urlpatterns() ) ),
]

urlpatterns += [
    url(r'^admin/login/$', RedirectView.as_view(url='/login/', permanent=True), name='go-to-login'),
    url(r'^admin/logout/$', RedirectView.as_view(url='/logout/', permanent=True),name='go-to-logout' ),
    url(r'^admin/', include(admin.site.urls)),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboards/project/cmdb/models.py
#coding:utf-8
from django.db import models
from django.db import IntegrityError
from authority.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.db.models import Count
from utils.ansibclient import AnsibleAPI
from utils.saltapi import SaltAPI


@python_2_unicode_compatible 
class Asset(models.Model):
    """
    资产总表
    """
    
    asset_types = (
        (1, '服务器'),
        (2, '网络设备'),
        (3, '存储设备'),
        (4, '安全设备'),
        (5, '软件资产'),
    )

    asset_status = (
        (0, '在线'),
        (1, '下线'),
        (2, '未知'),
        (3, '故障'),
        (4, '备用'),
    )

    sn = models.CharField(max_length=128, unique=True, verbose_name="资产序列号")
    name = models.CharField(max_length=64, unique=True, verbose_name="资产名称")
    category = models.SmallIntegerField(choices=asset_types, default=1, verbose_name='资产类型')
    oem = models.ForeignKey('Manufacturer', null=True, blank=True, verbose_name='制造商')
    contract = models.ForeignKey('Contract', null=True, blank=True, verbose_name='合同')
    status = models.SmallIntegerField(choices=asset_status, default=0, verbose_name='资产状态')
    tags = models.ManyToManyField('Tag', blank=True, verbose_name='标签')
    memo = models.TextField(null=True, blank=True, verbose_name='备注')
    admin = models.ForeignKey(User, null=True, blank=True, verbose_name='资产管理员', related_name='admin')
    approved_by = models.ForeignKey(User, null=True, blank=True, verbose_name='批准人', related_name='approved_by')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='批准日期')
    updated_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')

    def __str__(self):
        return '<%s>  %s' % (self.get_category_display(), self.name)

    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']


@python_2_unicode_compatible
class ServerDevice(models.Model):
    """
    服务器设备
    """
    
    sub_types = (
        (1, '刀片机'),
        (2, '小型机'),
        (3, 'PC服务器'),
    )

    adding_ways = (
        ('auto', '自动添加'),
        ('manual', '手工录入'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE ) #联级删除
    category = models.SmallIntegerField(choices=sub_types, default=4, verbose_name='服务器类型')
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name='型号')
    cabinet = models.ForeignKey('Cabinet', null=True, blank=True, verbose_name='归属机柜')
    ordinal = models.CharField(max_length=30, null=True, blank=True, verbose_name='机柜序号')
    manageip = models.GenericIPAddressField(null=True, blank=True, verbose_name='管理IP')
    os_type = models.CharField(max_length=64, blank=True, null=True, verbose_name='系统类型')
    os_distribution = models.CharField(max_length=64, blank=True, null=True, verbose_name='发行版本')
    os_release = models.CharField(max_length=64, blank=True, null=True, verbose_name='系统版本')
    created_by = models.CharField(choices=adding_ways, max_length=32, default='auto', verbose_name="添加方式")

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_category_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = verbose_name


class SecurityDevice(models.Model):
    """
    安全设备
    """
    
    sub_types = (
        (1, '防火墙'),
        (2, '入侵检测设备'),
        (3, '互联网网关'),
        (4, '运维审计系统'),
    )

    asset = models.OneToOneField('Asset')
    category = models.SmallIntegerField(choices=sub_types, default=0, verbose_name="设备类型")

    def __str__(self):
        return self.asset.name + "--" + self.get_category_display() + " id:%s" % self.id

    class Meta:
        verbose_name = '安全设备'
        verbose_name_plural = verbose_name


class StorageDevice(models.Model):
    """
    存储设备
    """
    
    sub_types = (
        (1, '磁盘阵列'),
        (2, '网络存储器'),
        (3, '磁带库'),
        (4, '磁带机'),
    )

    asset = models.OneToOneField('Asset')
    category = models.SmallIntegerField(choices=sub_types, default=0, verbose_name="设备类型")

    def __str__(self):
        return self.asset.name + "--" + self.get_category_display() + " id:%s" % self.id

    class Meta:
        verbose_name = '存储设备'
        verbose_name_plural = verbose_name


class NetworkDevice(models.Model):
    """
    网络设备
    """
    
    sub_types = (
        (0, '路由器'),
        (1, '交换机'),
        (2, '负载均衡'),
        (4, 'VPN设备'),
    )

    asset = models.OneToOneField('Asset')
    category = models.SmallIntegerField(choices=sub_types, default=0, verbose_name="设备类型")
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name="设备型号")
    firmware = models.CharField(max_length=128, blank=True, null=True, verbose_name="设备固件版本")
    port_num = models.SmallIntegerField(null=True, blank=True, verbose_name="端口个数")
    vlan_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="VLanIP")
    intranet_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="内网IP")
    detail = models.TextField(null=True, blank=True, verbose_name="详细配置")

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_category_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '网络设备'
        verbose_name_plural = verbose_name


class Software(models.Model):
    """
    付费软件
    """
    sub_types = (
        (0, '操作系统'),
        (1, '办公\开发软件'),
        (2, '业务软件'),
    )

    category = models.SmallIntegerField(choices=sub_types, default=0, verbose_name="软件类型")
    license_num = models.IntegerField(default=1, verbose_name="授权数量")
    version = models.CharField(max_length=64, unique=True, help_text='例如: CentOS release 6.7 (Final)',
                               verbose_name='软件/系统版本')

    def __str__(self):
        return '%s--%s' % (self.get_category_display(), self.version)

    class Meta:
        verbose_name = '软件/系统'
        verbose_name_plural = verbose_name


class CPU(models.Model):
    """
    CPU组件
    """

    asset = models.OneToOneField('Asset')
    cpu_model = models.CharField(max_length=128, blank=True, null=True, verbose_name='CPU型号')
    cpu_count = models.PositiveSmallIntegerField(default=1, verbose_name='物理CPU个数')
    cpu_core_count = models.PositiveSmallIntegerField(default=1, verbose_name='CPU核数')

    def __str__(self):
        return self.asset.name + ":   " + self.cpu_model

    class Meta:
        verbose_name = 'CPU'
        verbose_name_plural = verbose_name


class RAM(models.Model):
    """
    内存组件
    """
    
    sn = models.CharField(max_length=128, blank=True, null=True, verbose_name='SN号')
    asset = models.ForeignKey('Asset')
    model = models.CharField(max_length=128, blank=True, null=True, verbose_name='内存型号')
    manufacturer = models.CharField(max_length=128, blank=True, null=True, verbose_name='制造商')
    slot = models.CharField(max_length=64, verbose_name='插槽')
    capacity = models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)')

    def __str__(self):
        return '%s: %s: %s: %s' % (self.asset.name, self.model, self.slot, self.capacity)

    class Meta:
        verbose_name = '内存'
        verbose_name_plural = verbose_name
        unique_together = ('asset', 'slot')  # 同一资产下的内存，根据插槽的不同，必须唯一


class Disk(models.Model):
    """
    硬盘组件
    """

    interface_types = (
        ('SATA', 'SATA'),
        ('SAS', 'SAS'),
        ('SCSI', 'SCSI'),
        ('SSD', 'SSD'),
        ('unknown', 'unknown'),
    )

    sn = models.CharField(max_length=128, verbose_name='SN号')
    asset = models.ForeignKey('Asset')
    slot = models.CharField(max_length=64, blank=True, null=True, verbose_name='插槽位')
    model = models.CharField(max_length=128, blank=True, null=True, verbose_name='型号')
    manufacturer = models.CharField(max_length=128, blank=True, null=True, verbose_name='磁盘制造商')
    capacity = models.FloatField(blank=True, null=True, verbose_name='磁盘大小(GB)')
    interface_type = models.CharField(max_length=16, choices=interface_types, default='unknown', verbose_name='接口类型')

    def __str__(self):
        return '%s:  %s:  %s:  %sGB' % (self.asset.name, self.model, self.slot, self.capacity)

    class Meta:
        verbose_name = '硬盘'
        verbose_name_plural = verbose_name
        unique_together = ('asset', 'sn')


class NIC(models.Model):
    """
    网卡组件
    """

    asset = models.ForeignKey('Asset')
    name = models.CharField(max_length=64, blank=True, null=True, verbose_name='名称')
    model = models.CharField(max_length=128, verbose_name='型号')
    mac = models.CharField(max_length=64, verbose_name='MAC地址')
    ip = models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')
    netmask = models.CharField(max_length=64, blank=True, null=True, verbose_name='掩码')
    #up = models.BooleanField(default=False)
    bonding = models.CharField(max_length=64, blank=True, null=True, verbose_name='绑定地址')

    def __str__(self):
        return '%s:  %s:  %s' % (self.asset.name, self.model, self.mac)

    class Meta:
        verbose_name = '网卡'
        verbose_name_plural = verbose_name
        unique_together = ('asset', 'model', 'mac')  # 资产、型号和mac必须联合唯一。防止虚拟机中的特殊情况发生错误。


@python_2_unicode_compatible 
class IDC(models.Model):
    """
    机房
    """
    name = models.CharField(max_length=64, unique=True, verbose_name='名称')
    address = models.CharField(max_length=64, unique=True, verbose_name='地址')
    phone = models.CharField(max_length=32, blank=True, null=True, verbose_name='联系人')
    memo = models.CharField(max_length=128, blank=True, null=True, verbose_name='备注')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机房'
        verbose_name_plural = verbose_name


@python_2_unicode_compatible         
class Cabinet(models.Model):
    """
    机柜
    """
    idc = models.ForeignKey('IDC')
    name = models.CharField(max_length=64, verbose_name='名称')

dashboards/project/cmdb/views.py
#coding:utf-8
import os
import json
from dashboards import urls
from django.views import generic
from django.conf import settings
from utils.response import CommonResponse
from authority.shortcuts import login_perm_required
from .models import Asset,IDC,Cabinet,VirtHost


@urls.register
class CmdbIndex(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/$'
    
    @login_perm_required(perm_check=True)
    def get(self, request, *args, **kwargs):
        return self._isupply_response(request, 'cmdb/cm_index.html', {})
        
        
@urls.register
class CmdbAsset(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/list/$'
    
    @login_perm_required(perm_check=True)
    def get(self, request, *args, **kwargs):
        assets = Asset.objects.all()
        return self._isupply_response(request, 'cmdb/cm_list.html', {'assets': assets})
        
@urls.register
class CmdbAssetDetail(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/detail/$'
    #url_regex = r'^cmdb/detail/(?P<asset_id>[0-9]+)/$'
    
    @login_perm_required(perm_check=True)
    def get(self, request, *args, **kwargs):
        id = request.GET.get('asset_id')
        asset = Asset.objects.get(id= id)
        return self._isupply_response(request, 'cmdb/cm_detail.html', {'asset': asset})

        
@urls.register
class CmdbRoom(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/room/$'
    
    @login_perm_required(perm_check=True)
    def get(self, request, *args, **kwargs):
        idcs = IDC.objects.all()
        for idc in idcs:
            devices = 0
            for cabinet in idc.cabinet_set.all():
                devices += len(cabinet.serverdevice_set.all())
            idc.devices = devices
        return self._isupply_response(request, 'cmdb/cm_room.html', {'idcs': idcs})
        
@urls.register
class CmdbCabinet(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/cabinet/$'
    
    @login_perm_required(perm_check=False)
    def get(self, request, *args, **kwargs):
        id = request.GET.get('idc_id')
        cabinets = Cabinet.objects.filter(idc_id= id)
        return self._isupply_response(request, 'cmdb/cm_cabinet.html', {'cabinets': cabinets})
        
    @login_perm_required(perm_check=False)
    def post(self, request, *args, **kwargs):
        devices = {}
        position = []
        cabinet_id = request.POST.get('cabinet_id')
        cabinet = Cabinet.objects.get(id= cabinet_id)
        for device in cabinet.serverdevice_set.all():
            start, end = device.ordinal.split(',')
            devices[start] = {'sn': device.asset.sn, 'space': int(end) - int(start) + 1 }
            position.append( start )
        data = {'name': cabinet.name, 
                'size': cabinet.size, 'devices': devices, 'position': position, 'idc': cabinet.idc.name, }
        return self._iresult( json.dumps(data) )
        
    
@urls.register
class CmdbVirtHost(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/virthost/$'
    
    @login_perm_required(perm_check=False)
    def get(self, request, *args, **kwargs):
        virthosts = VirtHost.objects.all()
        return self._isupply_response(request, 'cmdb/cm_virthost.html', {'virthosts': virthosts})
        
@urls.register
class VirtHostDetail(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/virthost/detail/$'
    
    @login_perm_required(perm_check=False)
    def get(self, request, *args, **kwargs):
        hostid = request.GET.get('id')
        virthost = VirtHost.objects.get(id=hostid)
        return self._isupply_response(request, 'cmdb/cm_virtdetail.html', {'virthost': virthost})


@urls.register
class VirtHostRefresh(generic.View, CommonResponse):
    
    url_regex = r'^cmdb/virthost/refresh/$'
    
    @login_perm_required(perm_check=False)
    def get(self, request, *args, **kwargs):
        hostid = request.GET.get('id')
        virtmachine = VirtHost.objects.get(id=hostid)
        stat = 'ok' if virtmachine.gather_facts() else 'error'
        return self._iresult(stat)

templates/cmdb/cm_detail.html
{% extends 'base.html'%}

    
{% block content %}

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <i class="fa fa-tags"></i><h3 class="box-title">概览</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive" >
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>SN</th>
                        <th>业务线</th>
                        <th>制造商</th>
                        <th>管理IP</th>
                        <th>机房</th>
                        <th>标签</th>
                        <th>更新日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.get_category_display }}</td>
                    <td>{{ asset.sn }}</td>
                    <td></td>
                    <td>{{ asset.oem|default:'N/A' }}</td>
                    <td>{{asset.serverdevice.manageip}}</td>
                    <td>{{ asset.idc|default:'N/A' }}</td>
                    <td>
                        {% for tag in asset.tags.all %}
                        <label class="label label-default">{{ tag.name }}</label>
                        {% empty %}
                            -
                        {% endfor %}
                    </td>
                    <td>{{ asset.updated_time }}</td>
                </tr>
                </tbody>
            </table>
            
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>合同</th>
                        <th>价格</th>
                        <th>购买日期</th>
                        <th>过保日期</th>
                        <th>管理员</th>
                        <th>批准人</th>
                        <th>备注</th>
                        <th>批准日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.contract.name|default:'N/A' }}</td>
                    <td>{{ asset.contract.price|default:'N/A' }}</td>
                    <td>{{ asset.contract.start_day|default:'N/A' }}</td>
                    <td>{{ asset.contract.end_day|default:'N/A' }}</td>
                    <td>{{ asset.admin|default:'N/A' }}</td>
                    <td>{{ asset.approved_by|default:'N/A' }}</td>
                    <td>{{ asset.memo|default:'N/A' }}</td>
                    <td>{{ asset.updated_time }}</td>
                </tr>
                </tbody>
            </table>
            
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      
      <div class="box">
        <div class="box-header with-border">
          <i class="fa fa-tags"></i><h3 class="box-title">服务器</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive" >
                <thead>
                    <tr>
                        <th>服务器类型</th>
                        <th>型号</th>
                        <th>宿主机</th>
                        <th>Raid类型</th>
                        <th>OS类型</th>
                        <th>OS发行版本</th>
                        <th>OS版本</th>
                        <th>添加方式</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.serverdevice.get_category_display }}</td>
                    <td>{{ asset.serverdevice.model|default:'N/A' }}</td>
                    <td>{{ asset.serverdevice.hosted_on.id|default:'N/A' }}</td>
                    <td>{{ asset.serverdevice.raid_type|default:'N/A' }}</td>
                    <td>{{ asset.serverdevice.os_type|default:'N/A' }}</td>
                    <td>{{ asset.serverdevice.os_distribution|default:'N/A' }}</td>
                    <td>{{ asset.serverdevice.os_release|default:'N/A' }}</td>
                    <td>{{ asset.serverdevice.get_created_by_display }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      
      <div class="box">
        <div class="box-header with-border">
          <i class="fa fa-tags"></i><h3 class="box-title">网卡</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive" >
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>名称</th>
                        <th>型号</th>
                        <th>MAC</th>
                        <th>IP</th>
                        <th>掩码</th>
                        <th>绑定地址</th>
                    </tr>
                </thead>
                <tbody>
                {% for nic in asset.nic_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ nic.name|default:'N/A' }}</td>
                        <td>{{ nic.model }}</td>
                        <td>{{ nic.mac  }}</td>
                        <td>{{ nic.ip|default:'N/A' }}</td>
                        <td>{{ nic.netmask|default:'N/A' }}</td>
                        <td>{{ nic.bonding|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      
      <div class="box">
        <div class="box-header with-border">
          <i class="fa fa-tags"></i><h3 class="box-title">CPU</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive" >
                <thead>
                    <tr>
                        <th  style="width: 45%">CPU型号</th>
                        <th  style="width: 15%">物理CPU个数</th>
                        <th>CPU核数</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.cpu.cpu_model|default:'N/A' }}</td>
                    <td>{{ asset.cpu.cpu_count|default:'1' }}</td>
                    <td>{{ asset.cpu.cpu_core_count|default:'1' }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      
      <div class="box">
        <div class="box-header with-border">
          <i class="fa fa-tags"></i><h3 class="box-title">内存</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive" >
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for ram in asset.ram_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ ram.model|default:'N/A' }}</td>
                        <td>{{ ram.capacity|default:'N/A' }}</td>
                        <td>{{ ram.slot }}</td>
                        <td>{{ ram.manufacturer|default:'N/A' }}</td>
                        <td>{{ ram.sn|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      
      <div class="box">
        <div class="box-header with-border">
          <i class="fa fa-tags"></i><h3 class="box-title">硬盘</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>接口类型</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for disk in asset.disk_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ disk.model|default:'N/A' }}</td>
                        <td>{{ disk.capacity|default:'N/A' }}</td>
                        <td>{{ disk.slot|default:'N/A'  }}</td>
                        <td>{{ disk.get_interface_type_display }}</td>
                        <td>{{ disk.manufacturer|default:'N/A' }}</td>
                        <td>{{ disk.sn}}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}

templates/cmdb/cm_room.html
{% extends 'base.html'%}


{% block content %}

<section class="content">
    

        <div class="box">
            <div class="box-header">
              <h3 class="box-title"></h3>
                
              <div class="box-tools" >
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <table class="table table-bordered">
                <tr>
                  <th>机房名称</th>
                  <th>机柜数量</th>
                  <th>设备数量</th>
                  <th>位置</th>
                  <th>联系人</th>
                  <th>备注</th>
                </tr>
                {% for idc in idcs %}
                <tr>
                  <td><a href="/cmdb/cabinet/?idc_id={{idc.id}}">{{ idc.name}}</a></td>
                  <td>{{ idc.cabinet_set.all|length|default:'N/A' }}</td>
                  <td>{{ idc.devices|default:'N/A' }}</td>
                  <td>{{ idc.address }}</td>
                  <td>{{ idc.phone|default:'N/A' }}</td>
                  <td>{{idc.memo| default:'N/A'}}</td>
                </tr>
                {% endfor %}
              </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">&laquo;</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">&raquo;</a></li>
              </ul>
            </div>
        </div>
        <!-- /.box -->

</section>

{% endblock %}